sudo: false
language: python

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install: pip install tox

script: tox
